# Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np  

In [3]:
print (np.__version__)

1.21.5


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
type(arr) #find type

numpy.ndarray

In [14]:
print (np.min(arr))# mimimum value

1


In [15]:
print (np.max(arr)) # max value

10


In [12]:
print (np.mean(arr)) # mean value

5.5


In [13]:
print (np.median(arr)) # median value

5.5


In [16]:
print (np.ptp(arr)) # range value

9


In [11]:
print(np.std(arr))# standard deviation value

2.8722813232690143


In [12]:
print(np.var(arr)) #variance 

8.25


In [13]:
print(np.average(arr)) #weighted average

5.5


In [18]:
print (np.percentile (arr,10)) #percential

1.9


In [20]:
arr = np.array([1,2,4,6,29,8,3])
print(np.sort(arr))

[ 1  2  3  4  6  8 29]


In [21]:
arr = np.array([[1,2,3,4],[8,7,5,6]]) # creat simple array
arr

array([[1, 2, 3, 4],
       [8, 7, 5, 6]])

In [24]:
#diamension of array
print (arr.ndim)

2


In [23]:
# shape of array
print(arr.shape)

(2, 4)


In [24]:
#location
print (arr.data)

# random number generator using numpy

In [25]:
from numpy import random
x= random.randint(100)
print(x)

21


In [26]:
from numpy import random
x= random.randint(100)
print(x)

77


In [27]:
from numpy import random
x= random.randint(1000)
print(x)

385


In [28]:
from numpy import random
x= random.randint(100)
print(x)

17


In [30]:
from numpy import random
x= random.randint(798)
print(x)

109


In [36]:
#float value
x= random.rand(22)
print(x)

[0.30132328 0.24935941 0.65011782 0.56295562 0.90668619 0.05458121
 0.77114908 0.56795571 0.75411881 0.9446635  0.77650287 0.4812046
 0.85652049 0.04560783 0.83117564 0.71360946 0.8662834  0.53975423
 0.4556353  0.51610698 0.25213635 0.66471112]


In [37]:
from numpy import random
x= random.randint(100, size=(10))
print(x)

[33 63 72 89 81 59 76 66 12 35]


In [39]:
from numpy import random
x= random.randint(100, size=(5,10))
print(x)

[[38 81  8 78 53 31  8 39 69 45]
 [74 86 93  1 79 43 43 91 10  9]
 [49 89 94 72 48 62 23 46 92 97]
 [ 8 92 93  1 11 19  9 44 61 73]
 [54 32 88 36 17 92 88 10 76 99]]


In [2]:
from numpy import random
random.seed(101)
x= random.randint(100, size=(5,10))
print(x)

[[95 11 81 70 63 87 75  9 77 40]
 [ 4 63 40 60 92 64  5 12 93 40]
 [49 83  8 29 59 34 44 72 19 10]
 [76 95 87  0 73  8 62 36 83 99]
 [28 63  7 10 52 56 38 73 52 18]]


# pratical 2.4 : creating scalars in numpy

In [3]:
#vactor
import numpy as np

list1 = [1 , 2 , 3]

list2 = [[10],
         [20],
        [30]]
vector1 = np.array(list1)
vector2 = np.array(list2)

print ("Horizontal vector")
print(vector1)
print("--------------------")

print ("vectical vector")

print(vector2)

Horizontal vector
[1 2 3]
--------------------
vectical vector
[[10]
 [20]
 [30]]


# 2.6 PRATICAL creating matrix in numpy

In [9]:

a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [7]:
a=np.matrix('1 2; 3 4')
print("via string input:\n",a ,"\n\n")
b =np.matrix ([[2 ,4 ,5],[3, 7,9]])
print("via arrar -like input: \n",b)

via string input:
 [[1 2]
 [3 4]] 


via arrar -like input: 
 [[2 4 5]
 [3 7 9]]


# 2.7 PRATICAL : matrix multiplication in numpy

In [10]:
import numpy as np
a=5
b=[[3,7],
  [6, 9]]
print (np.dot(a,b)) # (dot= multiplication)

[[15 35]
 [30 45]]


In [11]:
a=[[3,7],
  [6, 9]]

b=[[9,4],
  [2, 3]]
print(np.dot(a,b))

print("-------------")

print(np.dot(b,a))

[[41 33]
 [72 51]]
-------------
[[51 99]
 [24 41]]


In [12]:
A =([1,2,3],[5,7,6],[8,9,2])

np.transpose(A)


array([[1, 5, 8],
       [2, 7, 9],
       [3, 6, 2]])

# PRATICAL 2.8 : mesaure of centeral tendency using numpy

In [5]:
import numpy as np
d =[1,2,3,4,5,6,7,8,9,11,12,14,17,34,56,22,34,11,34,78,]

#first quartial (Q1)

Q1 = np.median(d[:10])

print(Q1)


#third quartial (Q1)

Q3 = np.median(d[10:])

print(Q3)

# interquratile range

IQR = Q3-Q1
print ("IQR = Q3-Q1=", IQR)



5.5
28.0
IQR = Q3-Q1= 22.5


# PRATICAL : 2.10 ARRAY BROADCASTING IN NUMPY

In [8]:
a= np.array([1.0,2.3,1.5])
b= np.array([1.2,3.4,5.8])
a*b

array([1.2 , 7.82, 8.7 ])

In [9]:
a= np.array([1.0,2.3,1.5])
b=2.8

a*b

array([2.8 , 6.44, 4.2 ])

# CALCULATE BMI OF CRICKET PLAYER

In [12]:
#Heights of player

hg_in = [61,62,63,62,64,66,65,64,68,69,71]

#convert inti numpy array

ht_np = np.array(hg_in)

#convert height from inch to meter by exposing it to 0.0245

ht_np = ht_np * 0.0245

ht_np

array([1.4945, 1.519 , 1.5435, 1.519 , 1.568 , 1.617 , 1.5925, 1.568 ,
       1.666 , 1.6905, 1.7395])

In [13]:
#weight of player
wt_pd = [100,123,99,98,88,90,109,132,121,90,98]
#convert inti array
wt_np =np.array(wt_pd)
#cnvert into pound 0.45
wt_np = wt_np * 0.45
wt_np

array([45.  , 55.35, 44.55, 44.1 , 39.6 , 40.5 , 49.05, 59.4 , 54.45,
       40.5 , 44.1 ])

In [14]:
#bmi calculation
BMI = wt_np/(ht_np ** 2)
BMI

array([20.1474773 , 23.98844394, 18.69969146, 19.11274395, 16.10657018,
       15.48941385, 19.34105365, 24.15985527, 19.61769101, 14.17178885,
       14.57436774])

In [15]:
BMI[9]

14.171788849793996

In [16]:
BMI[BMI<21]

array([20.1474773 , 18.69969146, 19.11274395, 16.10657018, 15.48941385,
       19.34105365, 19.61769101, 14.17178885, 14.57436774])

In [17]:
BMI[:4]

array([20.1474773 , 23.98844394, 18.69969146, 19.11274395])

In [18]:
#2D ARRAY FOR PLAYERS
import numpy as np
p= np.array([wt_np,ht_np])
p

array([[45.    , 55.35  , 44.55  , 44.1   , 39.6   , 40.5   , 49.05  ,
        59.4   , 54.45  , 40.5   , 44.1   ],
       [ 1.4945,  1.519 ,  1.5435,  1.519 ,  1.568 ,  1.617 ,  1.5925,
         1.568 ,  1.666 ,  1.6905,  1.7395]])

In [14]:
p[1][7]

1.568

In [15]:
p[1]

array([1.4945, 1.519 , 1.5435, 1.519 , 1.568 , 1.617 , 1.5925, 1.568 ,
       1.666 , 1.6905, 1.7395])

In [17]:
#transpose

PT = p.transpose()
PT

array([[45.    ,  1.4945],
       [55.35  ,  1.519 ],
       [44.55  ,  1.5435],
       [44.1   ,  1.519 ],
       [39.6   ,  1.568 ],
       [40.5   ,  1.617 ],
       [49.05  ,  1.5925],
       [59.4   ,  1.568 ],
       [54.45  ,  1.666 ],
       [40.5   ,  1.6905],
       [44.1   ,  1.7395]])

In [18]:
PT.shape

(11, 2)

In [23]:
#stastical and mathematical function on player data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))

#standard deviation

print(np.std(wt_np))

print(np.corrcoef(wt_np,ht_np))





46.96363636363637
44.550000000000004
516.6
6.390728046058422
[[ 1.         -0.16817279]
 [-0.16817279  1.        ]]


In [9]:
#find the area of class.

hg_in = [200,123,323,256,100,254,189,289,109,145]

#convert into numpy array

ht_np = np.array(hg_in)

ht_np = ht_np /12

ht_np

array([16.66666667, 10.25      , 26.91666667, 21.33333333,  8.33333333,
       21.16666667, 15.75      , 24.08333333,  9.08333333, 12.08333333])

In [8]:
wt_pd = [100,123,200,250,120,120,250,200,230,120]
#convert into array
wt_np =np.array(wt_pd)

wt_np = wt_np / 12
wt_np

array([ 8.33333333, 10.25      , 16.66666667, 20.83333333, 10.        ,
       10.        , 20.83333333, 16.66666667, 19.16666667, 10.        ])

In [10]:
dd_pd = [100,123,200,250,190,120,200,200,200,120]
#convert into array
dd_np =np.array(dd_pd)

dd_np = dd_np / 12
dd_np

array([ 8.33333333, 10.25      , 16.66666667, 20.83333333, 15.83333333,
       10.        , 16.66666667, 16.66666667, 16.66666667, 10.        ])

In [11]:
area = ht_np * wt_np *dd_np

area

array([1157.40740741, 1076.890625  , 7476.85185185, 9259.25925926,
       1319.44444444, 2116.66666667, 5468.75      , 6689.81481481,
       2901.62037037, 1208.33333333])

In [21]:
#2D ARRAY FOR CLASS
import numpy as np
p= np.array([wt_np,ht_np,dd_np])
p

C:\Users\sap\AppData\Local\Temp\ipykernel_15276\4107829274.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  p= np.array([wt_np,ht_np,dd_np])


array([array([45.  , 55.35, 44.55, 44.1 , 39.6 , 40.5 , 49.05, 59.4 , 54.45,
              40.5 , 44.1 ])                                                ,
       array([1.4945, 1.519 , 1.5435, 1.519 , 1.568 , 1.617 , 1.5925, 1.568 ,
              1.666 , 1.6905, 1.7395])                                       ,
       array([ 8.33333333, 10.25      , 16.66666667, 20.83333333, 15.83333333,
              10.        , 16.66666667, 16.66666667, 16.66666667, 10.        ])],
      dtype=object)

In [20]:
#transpose

PT = p.transpose()
PT

array([array([45.  , 55.35, 44.55, 44.1 , 39.6 , 40.5 , 49.05, 59.4 , 54.45,
              40.5 , 44.1 ])                                                ,
       array([1.4945, 1.519 , 1.5435, 1.519 , 1.568 , 1.617 , 1.5925, 1.568 ,
              1.666 , 1.6905, 1.7395])                                       ,
       array([ 8.33333333, 10.25      , 16.66666667, 20.83333333, 15.83333333,
              10.        , 16.66666667, 16.66666667, 16.66666667, 10.        ])],
      dtype=object)